import { NextResponse } from "next/server";
import { getSQL } from "@/lib/db";
import { initSchema } from "@/lib/db";

export async function POST() {
  const sql = getSQL();

  await initSchema();

  // Drop and recreate to pick up new columns
  await sql`DROP TABLE IF EXISTS award_deals`;
  await initSchema();
  await sql`DELETE FROM points_programs`;

  // Seed programs
  await sql`INSERT INTO points_programs (name, transfer_partners) VALUES
    ('Chase Ultimate Rewards', ${JSON.stringify(["United MileagePlus", "Flying Blue", "British Airways Avios", "Southwest Rapid Rewards", "Singapore KrisFlyer"])}),
    ('Amex Membership Rewards', ${JSON.stringify(["Delta SkyMiles", "Flying Blue", "British Airways Avios", "ANA Mileage Club", "Singapore KrisFlyer", "Aeroplan"])}),
    ('Capital One Miles', ${JSON.stringify(["Flying Blue", "British Airways Avios", "Turkish Miles&Smiles", "Avianca LifeMiles", "Singapore KrisFlyer"])})
  `;

  const deals = [
    { origin: "BOS", destination: "MAD", origin_city: "Boston", destination_city: "Madrid", airline_program: "Flying Blue", operating_airline: "Air France", cabin_class: "economy", points_required: 34000, cash_price_usd: 850, departure_date: "2026-06-15", return_date: "2026-06-29", departure_time: "17:45", arrival_time: "06:30+1", duration_minutes: 465, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "BOS", destination: "LIS", origin_city: "Boston", destination_city: "Lisbon", airline_program: "Flying Blue", operating_airline: "TAP Portugal", cabin_class: "economy", points_required: 34000, cash_price_usd: 880, departure_date: "2026-06-10", return_date: "2026-06-24", departure_time: "20:30", arrival_time: "07:15+1", duration_minutes: 405, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "JFK", destination: "CDG", origin_city: "New York", destination_city: "Paris", airline_program: "Flying Blue", operating_airline: "Air France", cabin_class: "economy", points_required: 30000, cash_price_usd: 720, departure_date: "2026-07-01", return_date: "2026-07-15", departure_time: "18:00", arrival_time: "07:20+1", duration_minutes: 440, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "JFK", destination: "CDG", origin_city: "New York", destination_city: "Paris", airline_program: "Flying Blue", operating_airline: "Delta", cabin_class: "business", points_required: 72000, cash_price_usd: 4200, departure_date: "2026-07-01", return_date: "2026-07-15", departure_time: "19:30", arrival_time: "08:50+1", duration_minutes: 440, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "LAX", destination: "CDG", origin_city: "Los Angeles", destination_city: "Paris", airline_program: "Flying Blue", operating_airline: "Air France", cabin_class: "economy", points_required: 38000, cash_price_usd: 780, departure_date: "2026-06-20", return_date: "2026-07-04", departure_time: "16:25", arrival_time: "11:45+1", duration_minutes: 620, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "ORD", destination: "AMS", origin_city: "Chicago", destination_city: "Amsterdam", airline_program: "Flying Blue", operating_airline: "KLM", cabin_class: "economy", points_required: 32000, cash_price_usd: 690, departure_date: "2026-06-12", return_date: "2026-06-26", departure_time: "17:10", arrival_time: "07:30+1", duration_minutes: 500, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "BOS", destination: "NRT", origin_city: "Boston", destination_city: "Tokyo", airline_program: "United MileagePlus", operating_airline: "United", cabin_class: "economy", points_required: 60000, cash_price_usd: 1200, departure_date: "2026-09-01", return_date: "2026-09-15", departure_time: "10:15", arrival_time: "17:30+1", duration_minutes: 855, stops: 1, layover_airports: "ORD", is_round_trip: 1 },
    { origin: "SFO", destination: "NRT", origin_city: "San Francisco", destination_city: "Tokyo", airline_program: "United MileagePlus", operating_airline: "United", cabin_class: "economy", points_required: 50000, cash_price_usd: 950, departure_date: "2026-08-15", return_date: "2026-08-29", departure_time: "11:30", arrival_time: "14:45+1", duration_minutes: 675, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "EWR", destination: "LHR", origin_city: "Newark", destination_city: "London", airline_program: "United MileagePlus", operating_airline: "United", cabin_class: "economy", points_required: 45000, cash_price_usd: 820, departure_date: "2026-07-10", return_date: "2026-07-24", departure_time: "19:00", arrival_time: "07:10+1", duration_minutes: 430, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "IAD", destination: "FRA", origin_city: "Washington DC", destination_city: "Frankfurt", airline_program: "United MileagePlus", operating_airline: "Lufthansa", cabin_class: "business", points_required: 88000, cash_price_usd: 5100, departure_date: "2026-09-05", return_date: "2026-09-19", departure_time: "17:30", arrival_time: "07:15+1", duration_minutes: 465, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "BOS", destination: "DUB", origin_city: "Boston", destination_city: "Dublin", airline_program: "British Airways Avios", operating_airline: "Aer Lingus", cabin_class: "economy", points_required: 26000, cash_price_usd: 580, departure_date: "2026-06-20", return_date: "2026-07-04", departure_time: "21:00", arrival_time: "08:30+1", duration_minutes: 330, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "JFK", destination: "LHR", origin_city: "New York", destination_city: "London", airline_program: "British Airways Avios", operating_airline: "British Airways", cabin_class: "economy", points_required: 26000, cash_price_usd: 650, departure_date: "2026-07-05", return_date: "2026-07-19", departure_time: "20:15", arrival_time: "08:25+1", duration_minutes: 430, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "MIA", destination: "NAS", origin_city: "Miami", destination_city: "Nassau", airline_program: "British Airways Avios", operating_airline: "American Airlines", cabin_class: "economy", points_required: 9000, cash_price_usd: 320, departure_date: "2026-06-08", return_date: null, departure_time: "09:45", arrival_time: "11:20", duration_minutes: 55, stops: 0, layover_airports: null, is_round_trip: 0 },
    { origin: "ATL", destination: "FCO", origin_city: "Atlanta", destination_city: "Rome", airline_program: "Delta SkyMiles", operating_airline: "Delta", cabin_class: "economy", points_required: 48000, cash_price_usd: 920, departure_date: "2026-06-18", return_date: "2026-07-02", departure_time: "17:55", arrival_time: "09:10+1", duration_minutes: 575, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "JFK", destination: "BCN", origin_city: "New York", destination_city: "Barcelona", airline_program: "Delta SkyMiles", operating_airline: "Delta", cabin_class: "economy", points_required: 42000, cash_price_usd: 780, departure_date: "2026-07-15", return_date: "2026-07-29", departure_time: "18:30", arrival_time: "08:15+1", duration_minutes: 465, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "SEA", destination: "HND", origin_city: "Seattle", destination_city: "Tokyo", airline_program: "Delta SkyMiles", operating_airline: "Delta", cabin_class: "business", points_required: 120000, cash_price_usd: 6800, departure_date: "2026-08-01", return_date: "2026-08-15", departure_time: "12:00", arrival_time: "15:30+1", duration_minutes: 630, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "JFK", destination: "NRT", origin_city: "New York", destination_city: "Tokyo", airline_program: "ANA Mileage Club", operating_airline: "ANA", cabin_class: "business", points_required: 85000, cash_price_usd: 7500, departure_date: "2026-10-01", return_date: "2026-10-15", departure_time: "11:00", arrival_time: "14:00+1", duration_minutes: 840, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "LAX", destination: "NRT", origin_city: "Los Angeles", destination_city: "Tokyo", airline_program: "ANA Mileage Club", operating_airline: "ANA", cabin_class: "business", points_required: 85000, cash_price_usd: 7200, departure_date: "2026-09-15", return_date: "2026-09-29", departure_time: "13:15", arrival_time: "16:55+1", duration_minutes: 700, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "YYZ", destination: "LIS", origin_city: "Toronto", destination_city: "Lisbon", airline_program: "Aeroplan", operating_airline: "Air Canada", cabin_class: "economy", points_required: 40000, cash_price_usd: 820, departure_date: "2026-07-20", return_date: "2026-08-03", departure_time: "22:00", arrival_time: "10:15+1", duration_minutes: 435, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "BOS", destination: "FCO", origin_city: "Boston", destination_city: "Rome", airline_program: "Aeroplan", operating_airline: "Air Canada", cabin_class: "economy", points_required: 48000, cash_price_usd: 1050, departure_date: "2026-06-25", return_date: "2026-07-09", departure_time: "18:30", arrival_time: "11:45+1", duration_minutes: 615, stops: 1, layover_airports: "YYZ", is_round_trip: 1 },
    { origin: "BOS", destination: "BCN", origin_city: "Boston", destination_city: "Barcelona", airline_program: "Flying Blue", operating_airline: "Air France", cabin_class: "economy", points_required: 36000, cash_price_usd: 820, departure_date: "2026-06-22", return_date: "2026-07-06", departure_time: "21:15", arrival_time: "13:00+1", duration_minutes: 585, stops: 1, layover_airports: "CDG", is_round_trip: 1 },
    { origin: "BOS", destination: "FCO", origin_city: "Boston", destination_city: "Rome", airline_program: "United MileagePlus", operating_airline: "United", cabin_class: "economy", points_required: 55000, cash_price_usd: 1100, departure_date: "2026-07-05", return_date: "2026-07-19", departure_time: "16:00", arrival_time: "10:30+1", duration_minutes: 630, stops: 1, layover_airports: "EWR", is_round_trip: 1 },
    { origin: "BOS", destination: "LHR", origin_city: "Boston", destination_city: "London", airline_program: "British Airways Avios", operating_airline: "British Airways", cabin_class: "economy", points_required: 26000, cash_price_usd: 620, departure_date: "2026-06-18", return_date: "2026-07-02", departure_time: "19:45", arrival_time: "07:00+1", duration_minutes: 375, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "LAX", destination: "CUN", origin_city: "Los Angeles", destination_city: "Cancun", airline_program: "Delta SkyMiles", operating_airline: "Delta", cabin_class: "economy", points_required: 25000, cash_price_usd: 350, departure_date: "2026-06-20", return_date: "2026-06-27", departure_time: "08:00", arrival_time: "15:30", duration_minutes: 270, stops: 0, layover_airports: null, is_round_trip: 1 },
    { origin: "ORD", destination: "MIA", origin_city: "Chicago", destination_city: "Miami", airline_program: "United MileagePlus", operating_airline: "United", cabin_class: "economy", points_required: 15000, cash_price_usd: 180, departure_date: "2026-06-14", return_date: null, departure_time: "06:30", arrival_time: "10:45", duration_minutes: 195, stops: 0, layover_airports: null, is_round_trip: 0 },
  ];

  for (const d of deals) {
    const cpp = Math.round(((d.cash_price_usd * 100) / d.points_required) * 100) / 100;
    await sql`
      INSERT INTO award_deals (origin, destination, origin_city, destination_city, airline_program, operating_airline, cabin_class, points_required, cash_price_usd, cents_per_point, departure_date, return_date, departure_time, arrival_time, duration_minutes, stops, layover_airports, is_round_trip, source)
      VALUES (${d.origin}, ${d.destination}, ${d.origin_city}, ${d.destination_city}, ${d.airline_program}, ${d.operating_airline}, ${d.cabin_class}, ${d.points_required}, ${d.cash_price_usd}, ${cpp}, ${d.departure_date}, ${d.return_date}, ${d.departure_time}, ${d.arrival_time}, ${d.duration_minutes}, ${d.stops}, ${d.layover_airports}, ${d.is_round_trip}, 'mock')
    `;
  }

  return NextResponse.json({ success: true, deals_seeded: deals.length });
}
